# Generated by Django 3.0.3 on 2020-04-04 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_no', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('sem_year_taken', models.CharField(max_length=8)),
                ('expiration_date', models.DateField()),
                ('approved_status', models.CharField(max_length=1)),
                ('comment', models.CharField(max_length=150)),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transfer.School')),
            ],
        ),
    ]
